In [1]:
import pandas as pd

In [4]:
venda = {'data': ['15/02/2024', '16/02/2024'],
         'valor': [500, 300],
         'produto': ['feijao', 'arroz'],
         'qtde': [50,70],
         }
venda_df = pd.DataFrame(venda)

In [5]:
print(venda_df)

         data  valor produto  qtde
0  15/02/2024    500  feijao    50
1  16/02/2024    300   arroz    70

In [6]:
display(venda_df)

         data  valor produto  qtde
0  15/02/2024    500  feijao    50
1  16/02/2024    300   arroz    70

IMPORTAR ARQUIVOS A PARTIR DE PASTA EXCEL --> Exibe os primeiros e ultimos valores

In [7]:
vendas_df = pd.read_excel("Vendas.xlsx")
display(vendas_df)

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,1,2019-01-01,Iguatemi Esplanada,Sapato Estampa,1,358,358
1,1,2019-01-01,Iguatemi Esplanada,Camiseta,2,180,360
2,1,2019-01-01,Iguatemi Esplanada,Sapato Xadrez,1,368,368
3,2,2019-01-02,Norte Shopping,Relógio,3,200,600
4,2,2019-01-02,Norte Shopping,Chinelo Liso,1,71,71
...,...,...,...,...,...,...,...
93905,65012,2019-11-30,Shopping Vila Velha,Mochila Xadrez,2,283,566
93906,65013,2019-11-30,Ribeirão Shopping,Pulseira Listrado,2,79,158
93907,65013,2019-11-30,Ribeirão Shopping,Cueca Listrado,3,67,201
93908,65014,2019-11-30,Shopping Morumbi,Pulseira Linho,5,114,570
93909,65014,2019-11-30,Shopping Morumbi,Casaco Xadrez,4,259,1036

Resumos três tipos vizualizações de Dados:
- head --> mostra as linhas de acordo com o parametro que passar no head(inicia com as 5 primeiras)
- shape --> quantas linhas e quantas colunas tem 
- describe --> mostra resumo(pega colunas numericas) da a quantidade de itens

In [9]:
print(vendas_df.shape)

(93910, 7)

In [10]:
display(vendas_df.describe())

       Código Venda    Quantidade  Valor Unitário   Valor Final
count  93910.000000  93910.000000    93910.000000  93910.000000
mean   32464.762155      2.166553      191.725886    414.862656
std    18809.007093      1.258732      145.215519    434.846228
min        1.000000      1.000000       30.000000     30.000000
25%    16204.000000      1.000000      100.000000    156.000000
50%    32367.000000      2.000000      155.000000    274.000000
75%    48793.750000      3.000000      248.000000    524.000000
max    65014.000000      5.000000      750.000000   3750.000000

In [8]:
display(vendas_df.head())

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,1,2019-01-01,Iguatemi Esplanada,Sapato Estampa,1,358,358
1,1,2019-01-01,Iguatemi Esplanada,Camiseta,2,180,360
2,1,2019-01-01,Iguatemi Esplanada,Sapato Xadrez,1,368,368
3,2,2019-01-02,Norte Shopping,Relógio,3,200,600
4,2,2019-01-02,Norte Shopping,Chinelo Liso,1,71,71

Editar tabela --> Pegar apenas colunas especificas

In [13]:
produtos = vendas_df[['Produto', 'ID Loja']]
display(produtos)

                 Produto              ID Loja
0         Sapato Estampa   Iguatemi Esplanada
1               Camiseta   Iguatemi Esplanada
2          Sapato Xadrez   Iguatemi Esplanada
3                Relógio       Norte Shopping
4           Chinelo Liso       Norte Shopping
...                  ...                  ...
93905     Mochila Xadrez  Shopping Vila Velha
93906  Pulseira Listrado    Ribeirão Shopping
93907     Cueca Listrado    Ribeirão Shopping
93908     Pulseira Linho     Shopping Morumbi
93909      Casaco Xadrez     Shopping Morumbi

[93910 rows x 2 columns]

Metodo .loc --> Pegar linha de acordo com uma condição(colunas e linhas)

In [15]:
# Pegar 5 linhas
#display(vendas_df.loc[1:5])

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
1,1,2019-01-01,Iguatemi Esplanada,Camiseta,2,180,360
2,1,2019-01-01,Iguatemi Esplanada,Sapato Xadrez,1,368,368
3,2,2019-01-02,Norte Shopping,Relógio,3,200,600
4,2,2019-01-02,Norte Shopping,Chinelo Liso,1,71,71
5,3,2019-01-02,Rio Mar Shopping Fortaleza,Cinto Linho,1,248,248

In [16]:
#Pegar linhas que correspondem a uma condição
vendas_norteshopping_df = vendas_df.loc[vendas_df['ID Loja'] == 'Norte Shopping']

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
3,2,2019-01-02,Norte Shopping,Relógio,3,200,600
4,2,2019-01-02,Norte Shopping,Chinelo Liso,1,71,71
8,7,2019-01-02,Norte Shopping,Camisa Gola V Listrado,1,116,116
9,7,2019-01-02,Norte Shopping,Camisa Liso,1,105,105
100,73,2019-01-02,Norte Shopping,Cueca Xadrez,5,60,300
...,...,...,...,...,...,...,...
93716,64888,2019-11-30,Norte Shopping,Polo Xadrez,1,142,142
93754,64914,2019-11-30,Norte Shopping,Calça Liso,1,190,190
93755,64914,2019-11-30,Norte Shopping,Casaco Estampa,2,256,512
93756,64914,2019-11-30,Norte Shopping,Gorro,2,80,160
93852,64980,2019-11-30,Norte Shopping,Bermuda Linho,1,195,195

In [18]:
#pegar varias linhas e colunas usando .loc
#.loc[linhas, colunas]
vendas_norteshopping_df = vendas_df.loc[vendas_df['ID Loja'] == 'Norte Shopping', ["ID Loja", "Produto", "Quantidade"]]
display(vendas_norteshopping_df)

              ID Loja                 Produto  Quantidade
3      Norte Shopping                 Relógio           3
4      Norte Shopping            Chinelo Liso           1
8      Norte Shopping  Camisa Gola V Listrado           1
9      Norte Shopping             Camisa Liso           1
100    Norte Shopping            Cueca Xadrez           5
...               ...                     ...         ...
93716  Norte Shopping             Polo Xadrez           1
93754  Norte Shopping              Calça Liso           1
93755  Norte Shopping          Casaco Estampa           2
93756  Norte Shopping                   Gorro           2
93852  Norte Shopping           Bermuda Linho           1

[3924 rows x 3 columns]

In [19]:
#Pegar algo especifico(1 valor)
#Passar linha dele e coluna dele

print(vendas_df.loc[1, 'Produto'])

Camiseta

Adicionar 1 Coluna nova ou Linha

In [20]:
# a partir de uma coluna que existe
# criar coluna comissão valor_final x 0.05
vendas_df['Comissão'] = vendas_df['Valor Final'] * 0.05
display(vendas_df)

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final,Comissão
0,1,2019-01-01,Iguatemi Esplanada,Sapato Estampa,1,358,358,17.90
1,1,2019-01-01,Iguatemi Esplanada,Camiseta,2,180,360,18.00
2,1,2019-01-01,Iguatemi Esplanada,Sapato Xadrez,1,368,368,18.40
3,2,2019-01-02,Norte Shopping,Relógio,3,200,600,30.00
4,2,2019-01-02,Norte Shopping,Chinelo Liso,1,71,71,3.55
...,...,...,...,...,...,...,...,...
93905,65012,2019-11-30,Shopping Vila Velha,Mochila Xadrez,2,283,566,28.30
93906,65013,2019-11-30,Ribeirão Shopping,Pulseira Listrado,2,79,158,7.90
93907,65013,2019-11-30,Ribeirão Shopping,Cueca Listrado,3,67,201,10.05
93908,65014,2019-11-30,Shopping Morumbi,Pulseira Linho,5,114,570,28.50
93909,65014,2019-11-30,Shopping Morumbi,Casaco Xadrez,4,259,1036,51.80

In [21]:
#criar uma coluna nova com valor padrão
#Coluna de imposto preencher todos valores com 0
vendas_df.loc[:, "Imposto"] = 0
display(vendas_df)

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final,Comissão,Imposto
0,1,2019-01-01,Iguatemi Esplanada,Sapato Estampa,1,358,358,17.90,0
1,1,2019-01-01,Iguatemi Esplanada,Camiseta,2,180,360,18.00,0
2,1,2019-01-01,Iguatemi Esplanada,Sapato Xadrez,1,368,368,18.40,0
3,2,2019-01-02,Norte Shopping,Relógio,3,200,600,30.00,0
4,2,2019-01-02,Norte Shopping,Chinelo Liso,1,71,71,3.55,0
...,...,...,...,...,...,...,...,...,...
93905,65012,2019-11-30,Shopping Vila Velha,Mochila Xadrez,2,283,566,28.30,0
93906,65013,2019-11-30,Ribeirão Shopping,Pulseira Listrado,2,79,158,7.90,0
93907,65013,2019-11-30,Ribeirão Shopping,Cueca Listrado,3,67,201,10.05,0
93908,65014,2019-11-30,Shopping Morumbi,Pulseira Linho,5,114,570,28.50,0
93909,65014,2019-11-30,Shopping Morumbi,Casaco Xadrez,4,259,1036,51.80,0

In [22]:
# Importando e lendo nova planilha
vendas_dez_df = pd.read_excel("Vendas - Dez.xlsx")
display(vendas_dez_df)

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,65014,2019-12-01,Shopping Morumbi,Sunga Listrado,5,114,570
1,65014,2019-12-01,Shopping Morumbi,Casaco Listrado,1,269,269
2,65016,2019-12-01,Iguatemi Campinas,Sapato Listrado,2,363,726
3,65016,2019-12-01,Iguatemi Campinas,Casaco,1,250,250
4,65017,2019-12-01,Shopping SP Market,Gorro Liso,3,92,276
...,...,...,...,...,...,...,...
7084,69996,2019-12-26,Center Shopping Uberlândia,Short Listrado,2,102,204
7085,69996,2019-12-26,Center Shopping Uberlândia,Mochila,4,270,1080
7086,69996,2019-12-26,Center Shopping Uberlândia,Pulseira Estampa,1,87,87
7087,69997,2019-12-26,Ribeirão Shopping,Camisa Listrado,1,108,108
7088,69997,2019-12-26,Ribeirão Shopping,Short Linho,2,133,266

In [23]:
# Adicionar vendas dez ao Vendas  
vendas_df = vendas_df.append(vendas_dez_df)
display(vendas_df)

C:\Users\bibic\AppData\Local\Temp\ipykernel_7544\1334500124.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  vendas_df = vendas_df.append(vendas_dez_df)

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final,Comissão,Imposto
0,1,2019-01-01,Iguatemi Esplanada,Sapato Estampa,1,358,358,17.90,0.0
1,1,2019-01-01,Iguatemi Esplanada,Camiseta,2,180,360,18.00,0.0
2,1,2019-01-01,Iguatemi Esplanada,Sapato Xadrez,1,368,368,18.40,0.0
3,2,2019-01-02,Norte Shopping,Relógio,3,200,600,30.00,0.0
4,2,2019-01-02,Norte Shopping,Chinelo Liso,1,71,71,3.55,0.0
...,...,...,...,...,...,...,...,...,...
7084,69996,2019-12-26,Center Shopping Uberlândia,Short Listrado,2,102,204,NaN,NaN
7085,69996,2019-12-26,Center Shopping Uberlândia,Mochila,4,270,1080,NaN,NaN
7086,69996,2019-12-26,Center Shopping Uberlândia,Pulseira Estampa,1,87,87,NaN,NaN
7087,69997,2019-12-26,Ribeirão Shopping,Camisa Listrado,1,108,108,NaN,NaN
7088,69997,2019-12-26,Ribeirão Shopping,Short Linho,2,133,266,NaN,NaN

 excluir linhas e colunas

In [25]:
# 1 eixo da coluna 0 eixo da linha
vendas_df = vendas_df.drop(0, axis=0)
display(vendas_df)

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final,Comissão
1,1,2019-01-01,Iguatemi Esplanada,Camiseta,2,180,360,18.00
2,1,2019-01-01,Iguatemi Esplanada,Sapato Xadrez,1,368,368,18.40
3,2,2019-01-02,Norte Shopping,Relógio,3,200,600,30.00
4,2,2019-01-02,Norte Shopping,Chinelo Liso,1,71,71,3.55
5,3,2019-01-02,Rio Mar Shopping Fortaleza,Cinto Linho,1,248,248,12.40
...,...,...,...,...,...,...,...,...
7084,69996,2019-12-26,Center Shopping Uberlândia,Short Listrado,2,102,204,NaN
7085,69996,2019-12-26,Center Shopping Uberlândia,Mochila,4,270,1080,NaN
7086,69996,2019-12-26,Center Shopping Uberlândia,Pulseira Estampa,1,87,87,NaN
7087,69997,2019-12-26,Ribeirão Shopping,Camisa Listrado,1,108,108,NaN
7088,69997,2019-12-26,Ribeirão Shopping,Short Linho,2,133,266,NaN

Tratar valores vazios (Nann)

In [ ]:
#deletar linhas e colunas completamente vazias
vendas_df =  vendas_df.dropna(how='all', axis=1)

In [ ]:
# Se tiver pelo menos 1 valor vazio(excluir)
vandas_df =  vendas_df.dropna()

In [26]:
# preencher valores vazios com a media da coluna
vendas_df['Comissão'] = vendas_df['Comissão'].fillna(vendas_df['Comissão'].mean())
display(vendas_df)

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final,Comissão
1,1,2019-01-01,Iguatemi Esplanada,Camiseta,2,180,360,18.000000
2,1,2019-01-01,Iguatemi Esplanada,Sapato Xadrez,1,368,368,18.400000
3,2,2019-01-02,Norte Shopping,Relógio,3,200,600,30.000000
4,2,2019-01-02,Norte Shopping,Chinelo Liso,1,71,71,3.550000
5,3,2019-01-02,Rio Mar Shopping Fortaleza,Cinto Linho,1,248,248,12.400000
...,...,...,...,...,...,...,...,...
7084,69996,2019-12-26,Center Shopping Uberlândia,Short Listrado,2,102,204,20.743163
7085,69996,2019-12-26,Center Shopping Uberlândia,Mochila,4,270,1080,20.743163
7086,69996,2019-12-26,Center Shopping Uberlândia,Pulseira Estampa,1,87,87,20.743163
7087,69997,2019-12-26,Ribeirão Shopping,Camisa Listrado,1,108,108,20.743163
7088,69997,2019-12-26,Ribeirão Shopping,Short Linho,2,133,266,20.743163

In [ ]:
# preencher com o ultimo valor
#ffill --> preenche com o valor que esta acima dele
vendas_df = vendas_df.ffill()

Calcular indicadores

In [27]:
# quantas transações teve por loja
# value_counts --> quantos valores aparecem 
trans_lojas = vendas_df['ID Loja'].value_counts()
display(trans_lojas)

Shopping Vila Velha                 4234
Palladium Shopping Curitiba         4210
Norte Shopping                      4179
Rio Mar Shopping Fortaleza          4118
Bourbon Shopping SP                 4116
Iguatemi Campinas                   4108
Rio Mar Recife                      4099
Shopping Center Leste Aricanduva    4093
Shopping SP Market                  4080
Shopping Ibirapuera                 4051
Novo Shopping Ribeirão Preto        4049
Ribeirão Shopping                   4048
Salvador Shopping                   4030
Shopping Center Interlagos          4021
Shopping Iguatemi Fortaleza         4021
Center Shopping Uberlândia          4013
Shopping Eldorado                   4002
Passei das Águas Shopping           4000
Shopping União de Osasco            3995
Iguatemi Esplanada                  3979
Shopping Barra                      3962
Shopping Morumbi                    3959
Parque Dom Pedro Shopping           3902
Shopping Recife                     3891
Shopping Midway Mall                3837
Name: ID Loja, dtype: int64

In [28]:
# Faturamento de cada um dos produtos(tabela com todos os produtos, valor final somado)
# quando agrupar somar a coluna de valor final  

faturamento_produto = vendas_df.groupby('Produto').sum()
display(faturamento_produto)

C:\Users\bibic\AppData\Local\Temp\ipykernel_7544\1480231231.py:4: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  faturamento_produto = vendas_df.groupby('Produto').sum()

,Código Venda,Quantidade,Valor Unitário,Valor Final,Comissão
Produto,,,,,
Bermuda,29736664,1815,124950,272250,13913.846621
Bermuda Estampa,28011111,1726,135538,291694,14671.614990
Bermuda Linho,32794909,2024,179010,394680,19722.082947
Bermuda Liso,28019004,1756,127170,275692,13763.149175
Bermuda Listrado,29304435,1799,138224,293237,14792.123968
...,...,...,...,...,...
Tênis Estampa,29267679,1788,215040,457728,22448.017131
Tênis Linho,29440230,1832,249900,538608,26384.203458
Tênis Liso,30105216,1784,221046,474544,23269.389784
Tênis Listrado,28850195,1836,220604,481032,23771.114990
Tênis Xadrez,29758793,1775,219891,459725,22630.080805

In [29]:
#mostrar so produto e valor final 
# Realizei primeiro o parametro que queria como retorno --> ['Produto', 'Valor Final']
faturamento_produto = vendas_df[['Produto', 'Valor Final']].groupby('Produto').sum()
display(faturamento_produto)

                  Valor Final
Produto
Bermuda                272250
Bermuda Estampa        291694
Bermuda Linho          394680
Bermuda Liso           275692
Bermuda Listrado       293237
...                       ...
Tênis Estampa          457728
Tênis Linho            538608
Tênis Liso             474544
Tênis Listrado         481032
Tênis Xadrez           459725

[120 rows x 1 columns]

Mesclar 2 dataframes (Procurar informações de 1 dataframe no outro)

In [35]:
gerentes_df = pd.read_excel("Gerentes.xlsx")
display(gerentes_df)

                             ID Loja   Gerente
0                 Iguatemi Esplanada  Salvador
1                     Norte Shopping     Joana
2         Rio Mar Shopping Fortaleza     Maria
3                     Shopping Barra   Letícia
4                Shopping Ibirapuera    Helena
5                  Iguatemi Campinas     Luiza
6   Shopping Center Leste Aricanduva     Julia
7          Passei das Águas Shopping    Nicole
8                    Shopping Recife     André
9               Shopping Midway Mall      João
10               Bourbon Shopping SP    Marcus
11        Shopping Center Interlagos    Amanda
12         Parque Dom Pedro Shopping     Carol
13        Center Shopping Uberlândia  Andressa
14          Shopping União de Osasco     Lilia
15                 Shopping Eldorado     Paulo
16               Shopping Vila Velha     Pablo
17      Novo Shopping Ribeirão Preto     Diana
18                    Rio Mar Recife       Ana
19       Palladium Shopping Curitiba    Flavia
20                Shopping SP Market  Fernanda
21                 Ribeirão Shopping     Fábio
22       Shopping Iguatemi Fortaleza      Joel
23                  Shopping Morumbi    Gisele
24                 Salvador Shopping    Mateus

In [36]:
# Fazer com que  Tabela vendas_df tenha a coluna gerentes  
vendas_df = vendas_df.merge(gerentes_df)
display(vendas_df)

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final,Comissão,Gerente
0,1,2019-01-01,Iguatemi Esplanada,Camiseta,2,180,360,18.000000,Salvador
1,1,2019-01-01,Iguatemi Esplanada,Sapato Xadrez,1,368,368,18.400000,Salvador
2,21,2019-01-02,Iguatemi Esplanada,Camisa Gola V Listrado,2,116,232,11.600000,Salvador
3,34,2019-01-02,Iguatemi Esplanada,Sapato Listrado,1,363,363,18.150000,Salvador
4,34,2019-01-02,Iguatemi Esplanada,Camisa Gola V Liso,2,118,236,11.800000,Salvador
...,...,...,...,...,...,...,...,...,...
100992,69846,2019-12-25,Salvador Shopping,Short Estampa,2,96,192,20.743163,Mateus
100993,69846,2019-12-25,Salvador Shopping,Tênis Estampa,5,256,1280,20.743163,Mateus
100994,69850,2019-12-25,Salvador Shopping,Calça Estampa,4,177,708,20.743163,Mateus
100995,69972,2019-12-26,Salvador Shopping,Terno Liso,3,720,2160,20.743163,Mateus
100996,69972,2019-12-26,Salvador Shopping,Sapato Estampa,5,358,1790,20.743163,Mateus